
#ifndef __DBA___SETTLE_DAYS__H__INCLUDED__
#define __DBA___SETTLE_DAYS__H__INCLUDED__

#pragma once

class CSETTLEDAY_INSAccessor
{
public:
	CSETTLEDAY_INSAccessor()
	{
		memset(this, 0, sizeof(*this));
	}

	LONG m_RETURN_VALUE;

	TCHAR m_SETTLE_NAME[13];
	LONG m_DAYS;
	LONG m_ID;

	DEFINE_COMMAND_EX(CSETTLEDAY_INSAccessor, L"{ ? = CALL dbo.GQA_NewSettleCode(?, ?, ?) }");

	BEGIN_PARAM_MAP(CSETTLEDAY_INSAccessor)
		SET_PARAM_TYPE(DBPARAMIO_OUTPUT)
		COLUMN_ENTRY(1, m_RETURN_VALUE)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY(2, m_SETTLE_NAME)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY(3, m_DAYS)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY(4, m_ID)
	END_PARAM_MAP()
};

class CSETTLEDAY_DELAccessor
{
public:
	CSETTLEDAY_DELAccessor()
	{
		memset(this, 0, sizeof(*this));
	}

	LONG m_RETURN_VALUE;

	LONG m_SETTLE_ID;

	DEFINE_COMMAND_EX(CSETTLEDAY_DELAccessor, L"{ ? = CALL dbo.GQA_DelSettleCode(?) }");

	BEGIN_PARAM_MAP(CACCOUNT_DELAccessor)
		SET_PARAM_TYPE(DBPARAMIO_OUTPUT)
		COLUMN_ENTRY(1, m_RETURN_VALUE)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY(2, m_ACCOUNT_ID)
	END_PARAM_MAP()
};

#endif
