
#ifndef __DBA___TRADE_PARAMS__H__INCLUDED__
#define __DBA___TRADE_PARAMS__H__INCLUDED__

#pragma once

class CTCP_INSAccessor
{
public:
	CTCP_INSAccessor()
	{
		memset(this, 0, sizeof(*this));
	}

	LONG m_RETURN_VALUE;

	LONG m_FIRM_ID;
	LONG m_CLASS_ID;
	LONG m_ACCOUNT_ID;
	LONG m_CLIENT_ID;
	LONG m_MODE;
	LONG m_PARAM_ID;

	DBSTATUS m_dbsAccountID;
	DBSTATUS m_dbsClientID;

	DEFINE_COMMAND_EX(CTCP_INSAccessor, L"{ ? = CALL dbo.GQA_NewTradeCreationParams(?, ?, ?, ?, ?, ?) }");

	BEGIN_PARAM_MAP(CTCP_INSAccessor)
		SET_PARAM_TYPE(DBPARAMIO_OUTPUT)
		COLUMN_ENTRY(1, m_RETURN_VALUE)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY(2, m_FIRM_ID)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY(3, m_CLASS_ID)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY_STATUS(4, m_ACCOUNT_ID, m_dbsAccountID)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY_STATUS(5, m_CLIENT_ID, m_dbsClientID)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY(6, m_MODE)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY(7, m_PARAM_ID)
	END_PARAM_MAP()
};

class CTCP_DELAccessor
{
public:
	CTCP_DELAccessor()
	{
		memset(this, 0, sizeof(*this));
	}

	LONG m_RETURN_VALUE;

	LONG m_PARAM_ID;

	DEFINE_COMMAND_EX(CTCP_DELAccessor, L"{ ? = CALL dbo.GQA_DelTradeCreationParam(?) }");

	BEGIN_PARAM_MAP(CTCP_DELAccessor)
		SET_PARAM_TYPE(DBPARAMIO_OUTPUT)
		COLUMN_ENTRY(1, m_RETURN_VALUE)
		SET_PARAM_TYPE(DBPARAMIO_INPUT)
		COLUMN_ENTRY(2, m_PARAM_ID)
	END_PARAM_MAP()
};

#endif // __DBA___TRADE_PARAMS__H__INCLUDED__
